### PR TITLE
Fixing transaction id reference

### PR DESCRIPTION
**Pull request by anvyst**
Fixed the field name after troubleshooting the issue with Paysafe tech support. 

Apparently, `mb_transaction_id` should be the one carrying the reference to initial Neteller deposit in order to make a withdrawal to Neteller's client account.

UPD: @zhooravell , if there's a chance of reviewing and merge & tag it, it would be super great, so we could patch the app with the up-to-date fix :)

### CODE REVIEW

**Comment by zhooravell** [comment]
@anvyst, thank you for request pool
I think it's worth adding a new method. something like this
`public function setSkrillOriginalTransactionId(TransactionId $transactionId): self
    {
        $this->payload['mb_transaction_id'] = strval($transactionId);

        return $this;
    }
`
and it will cover all options.
https://www.skrill.com/fileadmin/content/pdf/Skrill_Automated_Payments_Interface_Guide.pdf
page 14
+
please fix PayoutRequest__construct() doc block

**Comment by anvyst** [comment]
@zhooravell do you suggest keeping the initial method that sets `transaction_id` (aka `PayoutRequest::setOriginalTransactionId(TransactionID)`)  and add a separate method (`PayoutRequest::setSkrillOriginalTransactionId(TransactionID)`) that will assign value to `mb_transaction_id`, right?

**Comment by zhooravell** [comment]
yes)

**Comment by anvyst** [comment]
@zhooravell done, have a look if you have any more comments on the PR :)

**Comment by anvyst** [comment]
@zhooravell , Roman, would you mind tagging it as well, so we'll pick it up from packagist?

**Comment by zhooravell** [comment]
@anvyst , done

**Pull request merged**
